# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage:  'vs2017-win2016' # other options: 'macOS-10.13', 'vs2017-win2016' or 'Ubuntu 16.04' 

  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'ConnectDevOpsWow86c7'
    WebAppName: 'AzureWebApp86c7 '
    Package: $(System.ArtifactsDirectory)/**/*.zip
